name: Production (Deployment)
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://docs.365extensions.com/docs/smp
    steps:
      - uses: actions/checkout@v2
      - name: Install Stoplight CLI
        run: sudo npm install -g @stoplight/cli
      - name: Deploy to Stoplight
        env:
          STOPLIGHT_TOKEN: ${{ secrets.STOPLIGHT_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          npx @stoplight/cli@5 push --ci-token $STOPLIGHT_TOKEN
