name: Release

on:
  push:
    branches: [release]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch to 365extensions-docs
        run: |
          curl -X POST https://api.github.com/repos/thetanz/365extensions-docs/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -H 'Content-Type: application/json' \
          -u "${{secrets.GH_USERNAME}}:${{secrets.GH_PERSONAL_ACCESS_TOKEN}}" \
          --data '{"event_type": "build" }'